# Math as a tool

## Warmup

Run the following lines in the cell below:

```
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

In [2]:
# imports here

%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Warmup 1: Write a one line function using set operations to verify that two given sets have NO elements in common. 

```
common_elements({1, 2, 3}, {2}) -> True
common_elements({1, 2, 3}, {'a', 'b', 'c'}) -> False
common_elements({1, 2, 3}, {'a', 1, 'hi!'}) -> True
```

In [12]:
# warmup 1

def common_elements(my2Sets):
    return my2Sets[0].intersection(my2Sets[1]) != set() #check if the intersection of the 2 sets is NOT equal to an empty set


#TESTS:
listOfSets = []
listOfSets.append(({1, 2, 3}, {2}))
listOfSets.append(({1, 2, 3}, {'a', 'b', 'c'}))
listOfSets.append(({1, 2, 3}, {'a', 1, 'hi!'}))

for i in listOfSets:
    print(common_elements(i))
    
    

True
False
True


## Exercise 1: Dot Product

Write a function `matrix_multiply(A, B)` using for loops, `+` and `*` that takes in two matrices (can be list of lists, or 2d numpy array) and returns their dot product (matrix multiplication). It should work with column vectors ($k \times 1$ dimensions) and row vectors ($1 \times k$) normally.


```import numpy as np

A = [
    [1,2,3],
    [4,5,6]
]

B = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

matrix_multiply(A,B)

RETURNS: 
[[30, 36, 42],
 [66, 81, 96]]

---------example 2-------------
# This is a row vector
A = np.array([
    [1,2,3]
])

# This is a column vector
B = np.array([
    [1],
    [4],
    [7]
])

matrix_multiply(A,B)

RETURNS:
[[30]]

```

Use `np.dot` to test your output

In [72]:
# exercise 1
def matrix_multiply(A, B):
    #transform A and B to a numpy arrays
    a = np.array(A)
    b = np.array(B)
    rowList = []
    returnMatrix =[]
    
    for indexRowA in range (0, a.shape[0]):    #1
        for indexColB in range(0,b.shape[1]):  #2 #5
            rowList.append((sum(a[indexRowA,:]*b[:,indexColB]))) #3 #4, 
        returnMatrix.append(rowList)   #6
        rowList = []                   #7
    return np.array(returnMatrix)      #8

#Algorithm: 
    #1- We Iterated through each row of A
    #2-    within which we iterated through each column of B
    #3-        We use numpy array to multiply A Rows * B Rows item by item
    #4-        Then we need to sum up the previous results from the multiplication: This gives us 1 item of a Row of the Matrix result
    #5-        the process is repeated until a full row is completed
    #6-    A completed result Matrix Row is added to a Result List
    #7-    The previous row is made empty for the next row processing
    #8- Once all rows of the result matrix have been completed, the result matrix is return in the shape of a numpy array


#TEST 
#A = [ [1,2,3]]
#B = [[1],[4], [7]]
A = [ [1,2,3],[4,5,6]]
B = [[1,2,3],[4,5,6], [7,8,9]]





print(f'Comparison of function result :\n { matrix_multiply(A, B) } \n vs\n np.dot result :\n {np.dot(A,B)}')




Comparison of function result :
 [[30 36 42]
 [66 81 96]] 
 vs
 np.dot result :
 [[30 36 42]
 [66 81 96]]


## Exercise 2: Matrix Math torture

**2.1** Give 3 examples of non-invertible square matrices that are non-zero

**2.2** Explain why the identity matrix $I$ is necessarily a square matrix with only $1$'s on the diagonal (hint: use the dot product from Q1)

**2.3** The **trace** is commutative for two matrices so $tr(AB) = tr(BA)$. Give an example where this is false for 3 matrices which can all be multiplied together.

**2.4** Give an example of a $4 \times 4$ idempotent matrix (where $A \cdot A = A^2 = A$)

**2.5** solve the following system of equations for `x`, `y` and `z` using matrices and `numpy.linalg.solve`

$$x 	+ 	y 	+ 	z 	= 	6$$

$$2y 	+ 	5z 	= 	−4$$

$$2x 	+ 	5y 	− 	z 	= 	27$$

In [177]:
# exercise 2.1
from scipy import linalg

#To be non invertible the determinant of a square matrix must be == 0
#A =
#|a b|
#|c d|
#The determinant is det = ad-cb

######################Ex1 : if ad = cb the determinant is 0
#so a=2, d=3, c=1, b=6
#|2 6|
#|1 3|
#shoud be not invertible. let's test
A = np.array([[2,6],[1,3]])
linalg.det(A) #=> answer is 0
#let's try to invert A
A_inv = linalg.inv(A) # \\ gives ERROR: LinAlgError: singular matrix. So Not invertible !!//

#######################Ex2: if ad = cb the determinant is 0
#so a=12, d=5, c=10, b=6
#|12 6|
#|10 5|
#shoud be not invertible. let's test
A = np.array([[12,6],[10,5]])
linalg.det(A) #=> answer is 0
#let's try to invert A
A_inv = linalg.inv(A) # \\ gives ERROR: LinAlgError: singular matrix. So Not invertible !! //

#######################Ex3: 
#A =
#|a b c|
#|d e f|
#|g h i|
#The determinant is det = aei + bfg + cdh - ceg - bdi - afh
#if (aei + bfg + cdh) = (ceg + bdi + afh) => the determinant is 0
#so aei=4, bfg=6, cdh=10, ceg=4, bdi=6, afh=10
#so a= 1, e=1, i=4, b=1, f=1, g=6, c=1, d=1 h=10,
#   c=1, e=1, g=4, b=1, d=1, i=6, a=1, f=1, h=10
#|1  1  1|
#|1  1  1|
#|6 10  4|
#shoud be not invertible. let's test
A = np.array([[1,1,1],[1,1,1],[6,10,4]])
linalg.det(A) #=> answer is 0
#let's try to invert A
A_inv = linalg.inv(A) # \\ gives ERROR: LinAlgError: singular matrix. So Not invertible !! //





LinAlgError: singular matrix

In [95]:
# exercise 2.2
# When a Matrix A_m.k is multiplied by The IDENTITY Matrix I_n.n:
# A_m.k @ I_n.n
# n MUST equal k. 
# (Basic requirement to multiply 2 Matrixes).
# The Identity diagonal fill out with 1. It has as many 1s as k.
# If the Identity Matrix as more or less columns than k, the resulting matrix would not have the same dimension as the initiale A_m.k Matrix

#Example if identity matrix is square:
identity= np.identity(3)

A = [               
    [1,2,3],
    [4,5,6]
]
#print(np.dot(A,identity))
print(f'GOOD Example if Identity matrix Square: \n{np.dot(A,identity)}')
print(f'the shape of A.I is IDENTICAL to A. Shape A.I ={np.dot(A,identity).shape}\n')


#Example, if IDENTITY Matrix is not square:
ex_IdentityMatrix_NOT_Square = [
    [1,0,0, 0],
    [0,1,0, 0],
    [0,0,1, 0]
]

print(f'Bad Example if Identity matrix NOT Square: \n{np.dot(A,C)}')
print(f'the shape of A.I is DIFFERENT to A. Shape A.IdentityMatrix_NOT_Square ={np.dot(A,ex_IdentityMatrix_NOT_Square).shape}\n')
#Result is : A_2.4,  But the shape should have been A_2,3
#[[1 2 3 0]
# [4 5 6 0]]

GOOD Example if Identity matrix Square: 
[[1. 2. 3.]
 [4. 5. 6.]]
the shape of A.I is IDENTICAL to A. Shape A.I =(2, 3)

Bad Example if Identity matrix NOT Square: 
[[1 2 3 0]
 [4 5 6 0]]
the shape of A.I is DIFFERENT to A. Shape A.IdentityMatrix_NOT_Square =(2, 4)



In [22]:
# exercise 2.3
from scipy import linalg
#the trace of matrix product must be cyclic to be equal
#Ex: tr(ABC)=tr(BCA)=tr(CAB)
#But tr(ABC)!=tr(ACB)
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) #A.Shape: 3.3
B = np.array([[1,2,5],[4,5,2],[7,8,1]]) #B.Shape: 3.3
C = np.array([[2,3,5],[6,3,1],[3,5,1]])     #C.Shape: 3.3

#TEST for cyclic matrix product: 
AB = np.dot(A,B)
ABC = np.dot(AB,C)
trace_ABC = np.trace(ABC)

BC = np.dot(B,C)
BCA = np.dot(BC,A)
trace_BCA = np.trace(BCA)

CA = np.dot(C,A)
CAB = np.dot(CA,B)
trace_CAB = np.trace(CAB)
trace_CAB

print(f' Does trace_ABC == trace_BCA == trace_CAB ?')
print(f' trace_ABC == trace_BCA : {trace_ABC == trace_BCA}')
print(f' trace_BCA == trace_CAB : {trace_BCA == trace_CAB} \n')


#Test for NON cyclic matrix product:
AC = np.dot(A,C)
ACB = np.dot(AC,B)
trace_CAB = np.trace(ACB)
trace_CAB
print(f' Does trace_ABC == trace_CAB ?')
print(f' trace_CAB : {trace_ABC == trace_CAB }')





 Does trace_ABC == trace_BCA == trace_CAB ?
 trace_ABC == trace_BCA : True
 trace_BCA == trace_CAB : True 

 Does trace_ABC == trace_CAB ?
 trace_CAB : False


In [197]:
# exercise 2.4
from numpy.linalg import matrix_power
#let's check wither the identity matrix is idempotent
identity1 = np.identity(4)
identity1
A_A = np.dot(identity1,identity1)
A_A
Asqr = matrix_power(identity1,2)
Asqr
#We have checked that 
#identity1 == A_A == Asqr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [122]:
# exercise 2.5
from scipy import linalg

# Solve this system:
# x+y+z=6
# 2y+5z=−4
# 2𝑥+5𝑦−𝑧=27


A = np.array([[1,1,1],[0,2,5],[2,5,-1]])
Y = np.array([[6],[-4],[27]])
print(f' Y= {Y} \n' )
print(f' A= {A} \n')
# Y = A.X
# We want to find X such that A^-1.Y = X

#1st Let's check whether A is Invertible i.e NonSingular:
linalg.det(A) # => returns -21: So the matrix is invertible
print(f'the determinant of A is det(A) = {linalg.det(A)} \n')
A_inv = linalg.inv(A)  # let's Compute the inverse of A
print(f'the inverted matrix A is A^-1 = {linalg.inv(A)}\n')

#2nd Let's calculate the product of A^-1.Y
solution = A_inv @ Y
solution  # Solution appeared to be array([[ 5.],[ 3.],[-2.]])
print(f'the solution X is X = {solution}\n')

#3 Let's verify the solution was the correct one
#if we multiply A.X we should find the initial Y vector
check = A @ solution
check  # The check gives back the initial Y vector Y = array([[ 6.], [-4.],[27.]])
print(f'if we multiply A.X we should find the initial Y vector = {check}\n')


print(' \\\ The solution is correctly found // ')

 Y= [[ 6]
 [-4]
 [27]] 

 A= [[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]] 

the determinant of A is det(A) = -21.0 

the inverted matrix A is A^-1 = [[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]

the solution X is X = [[ 5.]
 [ 3.]
 [-2.]]

if we multiply A.X we should find the initial Y vector = [[ 6.]
 [-4.]
 [27.]]

 \\ The solution is correctly found // 


## Exercise 3: Linear Algebra

Write each of the following systems of equations as a matrix and solve them using the numpy function from the lecture/pre-lecture.

HINT:

To solve the system for `a`, `b`, and `c`:

$$\begin{bmatrix} 2 & 1 & 2 \\ 1 & 5 & 3 \\ 4 & 1 & 2 \end{bmatrix} \begin{bmatrix} a \\ b \\ c \end{bmatrix} = \begin {bmatrix} 20\\ 38\\ 26 \end{bmatrix} $$

```
Matrix = np.array([[2,1,2], [1,5,3], [4,1,2]])
Solutions = np.array([20, 38, 26])
x = np.linalg.solve(Matrix, Solutions)
x
```

### Exercise 3.1

$$3x + 2y + z = 7$$
$$4x + 5y + 2z = 14$$
$$2x + 4y + 3z = 10$$


In [123]:
# exercise 3.1
Matrix = np.array([[3,2,1], [4,5,2], [2,4,3]])
Solutions = np.array([7, 14, 10])
x = np.linalg.solve(Matrix, Solutions)
x

array([1., 2., 0.])

### Exercise 3.2

$$3a + 3b + c = 16$$
$$2a + b + 3c = 11$$
$$4a + 2b + 5c = 21$$

In [124]:
# exercise 3.2
Matrix = np.array([[3,3,1], [2,1,3], [4,2,5]])
Solutions = np.array([16, 11, 21])
x = np.linalg.solve(Matrix, Solutions)
x


array([3., 2., 1.])

### Exercise 3.3

$$4i + 2j + k = 0$$
$$5i + j + 3k = 2$$
$$3i + 3j + 4k = 8$$

In [125]:
# exercise 3.3
Matrix = np.array([[4,2,1], [5,1,3], [3,3,4]])
Solutions = np.array([0, 3, 4])
x = np.linalg.solve(Matrix, Solutions)
x

array([-0.16666667, -0.36666667,  1.4       ])

## Exercise 4: Is it Prime?

A [prime number](https://en.wikipedia.org/wiki/Prime_number) is a number that can only be divided by 1 and by itself. 

Write a function that takes in a positive integer and returns `True` if it's prime and `False` otherwise.

```
check_prime(5) -> True
check_prime(13) -> True
check_prime(9) -> False
check_prime(15) -> False
```

In [172]:
# exercise 4
def check_prime(val):
    prime = True
    #any number is divisible by 1 and itself, so we only check within [2,val]
    #Beyonf val, if divided by a higher number, the results will not be integer, so not divisible
    
    vector = np.array(np.arange(2, val, 1))
    # y = a.x
    # x = y/a
    for a in vector:
        if val%a==0:
            prime=False
            break
    
    return prime


#TEST
print( ' 5 prime ->' + str(check_prime(5)) )
print( ' 13 prime ->' + str(check_prime(13)) )
print( ' 9 prime ->' + str(check_prime(9)) )
print( ' 15 prime ->' + str(check_prime(15)) )




 5 prime ->True
 13 prime ->True
 9 prime ->False
 15 prime ->False
